use num_enum::{IntoPrimitive, TryFromPrimitive};
use std::fmt::{Display, Formatter};

pub const TEAMS: [Team; 31] = [
    Team::All,
    Team::ArizonaDiamondbacks,
    Team::AtlantaBraves,
    Team::BaltimoreOrioles,
    Team::BostonRedSox,
    Team::ChicagoCubs,
    Team::ChicagoWhiteSox,
    Team::CincinnatiReds,
    Team::ClevelandGuardians,
    Team::ColoradoRockies,
    Team::DetroitTigers,
    Team::HoustonAstros,
    Team::KansasCityRoyals,
    Team::LosAngelesAngels,
    Team::LosAngelesDodgers,
    Team::MiamiMarlins,
    Team::MilwaukeeBrewers,
    Team::MinnesotaTwins,
    Team::NewYorkMets,
    Team::NewYorkYankees,
    Team::OaklandAthletics,
    Team::PhiladelphiaPhillies,
    Team::PittsburghPirates,
    Team::SanDiegoPadres,
    Team::SanFranciscoGiants,
    Team::SeattleMariners,
    Team::StLouisCardinals,
    Team::TampaBayRays,
    Team::TexasRangers,
    Team::TorontoBlueJays,
    Team::WashingtonNationals,
];

#[derive(IntoPrimitive, TryFromPrimitive, Copy, Clone, PartialEq)]
#[repr(u16)]
pub enum Team {
    All = 0,
    NewJerseyDevils = 1,
    NewYorkIslanders = 2,
    NewYorkRangers = 3,
    PhiladelphiaFlyers = 4,
    PittsburghPenguins = 5,
    BostonBruins = 6,
    BuffaloSabres = 7,
    MontrealCanadiens = 8,
    OttawaSenators = 9,
    TorontoMapleLeafs = 10,
    CarolinaHurricanes = 12,
    FloridaPanthers = 13,
    TampaBayLightning = 14,
    WashingtonCapitals = 15,
    ChicagoBlackhawks = 16,
    DetroitRedWings = 17,
    NashvillePredators = 18,
    StLouisBlues = 19,
    CalgaryFlames = 20,
    ColoradoAvalanche = 21,
    EdmontonOilers = 22,
    VancouverCanucks = 23,
    AnaheimDucks = 24,
    DallasStars = 25,
    LosAngelesKings = 26,
    SanJoseSharks = 28,
    ColumbusBlueJackets = 29,
    MinnesotaWild = 30,
    WinnipegJets = 52,
    ArizonaCoyotes = 53,
    VegasGoldenKnights = 54,
    SeattleKraken = 55,
}

impl Display for Team {
    fn fmt(&self, f: &mut Formatter<'_>) -> std::fmt::Result {
        match self {
            Team::All => write!(f, "All"),
            Team::NewJerseyDevils => write!(f, "New Jersey Devils"),
            Team::NewYorkIslanders => write!(f, "New York Islanders"),
            Team::NewYorkRangers => write!(f, "New York Rangers"),
            Team::PhiladelphiaFlyers => write!(f, "Philadelphia Flyers"),
            Team::PittsburghPenguins => write!(f, "Pittsburgh Penguins"),
            Team::BostonBruins => write!(f, "Boston Bruins"),
            Team::BuffaloSabres => write!(f, "Buffalo Sabres"),
            Team::MontrealCanadiens => write!(f, "Montreal Canadiens"),
            Team::OttawaSenators => write!(f, "Ottawa Senators"),
            Team::TorontoMapleLeafs => write!(f, "Toronto Maple Leafs"),
            Team::CarolinaHurricanes => write!(f, "Carolina Hurricanes"),
            Team::FloridaPanthers => write!(f, "Florida Panthers"),
            Team::TampaBayLightning => write!(f, "Tampa Bay Lightning"),
            Team::WashingtonCapitals => write!(f, "Washington Capitals"),
            Team::ChicagoBlackhawks => write!(f, "Chicago Blackhawks"),
            Team::DetroitRedWings => write!(f, "Detroit Red Wings"),
            Team::NashvillePredators => write!(f, "Nashville Predators"),
            Team::StLouisBlues => write!(f, "St. Louis Blues"),
            Team::CalgaryFlames => write!(f, "Calgary Flames"),
            Team::ColoradoAvalanche => write!(f, "Colorado Avalanche"),
            Team::EdmontonOilers => write!(f, "Edmonton Oilers"),
            Team::VancouverCanucks => write!(f, "Vancouver Canucks"),
            Team::AnaheimDucks => write!(f, "Anaheim Ducks"),
            Team::DallasStars => write!(f, "Dallas Stars"),
            Team::LosAngelesKings => write!(f, "Los Angeles Kings"),
            Team::SanJoseSharks => write!(f, "San Jose Sharks"),
            Team::ColumbusBlueJackets => write!(f, "Columbus Blue Jackets"),
            Team::MinnesotaWild => write!(f, "Minnesota Wild"),
            Team::WinnipegJets => write!(f, "Winnipeg Jets"),
            Team::ArizonaCoyotes => write!(f, "Arizona Coyotes"),
            Team::VegasGoldenKnights => write!(f, "Vegas Golden Knights"),
            Team::SeattleKraken => write!(f, "Seattle Kraken"),
        }
    }
}
